# Generated by Django 4.0.7 on 2022-09-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_api', '0003_alter_log_data_portfolio_linked'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='price_24h',
            field=models.FloatField(default=0),
        ),
    ]
