# Generated by Django 4.0.7 on 2022-09-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_api', '0004_asset_price_24h'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='asset',
            name='symbol',
            field=models.CharField(default='', max_length=255),
        ),
    ]
